---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - xtt.xyz
  resources:
  - geths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xtt.xyz
  resources:
  - geths/finalizers
  verbs:
  - update
- apiGroups:
  - xtt.xyz
  resources:
  - geths/status
  verbs:
  - get
  - patch
  - update
