apiVersion: xtt.xyz/v1
kind: Geth
metadata:
  name: geth-example
  namespace: default
spec:
  image: "ethereum/client-go:v1.10.26"
#  nodeType: "full"
  password: "123456"
  pvcName: geth-example-pvc
  cmd:
    - /bin/sh
    - -c
    - |
      ADDR=$(cat /data/account.txt) && \
      geth \
        --http \
        --networkid 6666 \
        --http.addr 0.0.0.0 \
        --http.port 8545 \
        --mine \
        --miner.threads 1 \
        --allow-insecure-unlock \
        --http.vhosts="*" \
        --http.api eth,net,web3,personal,admin,miner \
        --unlock $ADDR \
        --password /data/password.txt \
        --nodiscover \
        --datadir /data
  args: [""]
  env:
    ENV_VAR_1: "value1"
    ENV_VAR_2: "value2"
